name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        run: gcc -Iinclude src/fdir.c tests/test_fsm.c -o build_test && ./build_test
